export const data = [
  {
    id: 1,
    imgUrl: "/assets/images/avatar-mark-webber.webp",
    title: "Mark Webber",
    paragraph: "reacted to your recent post",
    focused: "My first tournament today!",
    time: "1m ago",
    isUnread: true,
  },
  {
    id: 2,
    imgUrl: "/assets/images/avatar-angela-gray.webp",
    title: "Angela Grey",
    paragraph: "followed you",
    time: "5m ago",
    isUnread: true,
  },
  {
    id: 3,
    imgUrl: "/assets/images/avatar-jacob-thompson.webp",
    title: "Jacob Thompson",
    paragraph: "has joined your group",
    focused: "Chess Club",
    time: "1 day ago",
    isUnread: true,
  },
  {
    id: 4,
    imgUrl: "/assets/images/avatar-rizky-hasanuddin.webp",
    title: "Rizky Hasanuddin",
    paragraph: "sent you a private message",
    message:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    time: "5 days ago",
    isUnread: false,
  },
  {
    id: 5,
    imgUrl: "/assets/images/avatar-kimberly-smith.webp",
    title: "Kimberly Smith",
    paragraph: "commented on you picture",
    time: "1 week ago",
    picture: "/assets/images/image-chess.webp",
    isUnread: false,
  },
  {
    id: 6,
    imgUrl: "/assets/images/avatar-nathan-peterson.webp",
    title: "Nathan Peterson",
    paragraph: "reacted to your recent post",
    focused: "5 end-game strategies to increase your win rate",
    time: "2 weeks ago",
    isUnread: false,
  },
  {
    id: 7,
    imgUrl: "/assets/images/avatar-anna-kim.webp",
    title: "Anna Kim",
    paragraph: "left the group",
    focused: "Chess Club",
    time: "2 weeks ago",
    isUnread: false,
  },
];
